---
  - name:  Create the new directory
    file:
      path:  '{{ item.directoryName }}'
      state:  directory
      owner:  '{{ item.owner }}'
      group:  '{{ item.group }}'
      mode:   '{{ item.mode }}'
    with_items:  '{{ newDirectories }}'