---
  - name:  Copy files from source system to the destination server.
    copy:
      src:     '{{ item.src }}'
      dest:    '{{ item.dest }}'
      owner:   '{{ item.owner }}'
      group:   '{{ item.group }}'
      mode:    '{{ item.mode }}'
    with_items:  '{{ copyFiles }}'